# Patterns defined in this file will be checked against every line of output (e.g. port scans and service scans)

# [[patterns]] 
#    description = 'Email address found: {match}'
#    pattern = '[\w.+-]+@[\w-]+\.[\w.-]+'

#[[patterns]] 
#    description = 'Subdomain found on {ipaddress}: {match}'
#    pattern = '(?![\d.]+)((?!-))(xn--)?[a-z0-9][a-z0-9-_]{0,61}[a-z0-9]{0,1}\.(xn--)?([a-z0-9\._-]{1,61}|[a-z0-9-]{1,30})'

#[[patterns]] 
#    description = 'IP address found on: {match}'
#    pattern = '(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})'

#[[pattern]]
#    description = 'CVE Identified: {match}'
#    pattern = '(CVE-\d{4}-\d{4,7})'
